In [1]:
import numpy as np

In [2]:
# 1D array
arr = np.array({10,20,30,40})
print(arr)

{40, 10, 20, 30}


In [7]:
# 2D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
# 3D array
arr = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,0]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 0]]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.np)

In [9]:
a=np.array([1,2,3,4])
b=np.zeros((3,4))
c=np.ones((2,3))
d=np.arange(0,20,2)
e=np.linspace(0,10,5)
print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3 4]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0.   2.5  5.   7.5 10. ]


In [10]:
# Vectorized Computation
arr = np.array([1,2,3,4,5])
result = arr*2
print(result)

[ 2  4  6  8 10]


In [11]:
list = (1,2,3,4,5)
result = list*2
print(result)

(1, 2, 3, 4, 5, 1, 2, 3, 4, 5)


In [14]:
arr = [1, 2, 3, 4, 5]

result = []

for i in arr:
    result.append(i * 2)

print(result)

[2, 4, 6, 8, 10]


In [16]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10
print(result)

[11 12 13 14 15]


In [18]:
arr = np.array([1,4,9,16,18])
print(np.sqrt(arr))

[1.         2.         3.         4.         4.24264069]


In [19]:
arr = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.array_equal(arr,arr2))

False


In [20]:
arr = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.array(arr+arr2))

[ 6  8 10 12]


In [21]:
arr = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.subtract(arr,arr2))

[-4 -4 -4 -4]


In [23]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)

[ 6  8 10 12]


In [24]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [25]:
arr = np.array([10,20,30,40])
print(arr > 20)

[False False  True  True]


In [27]:
arr = np.array([10,20,30,40])
passed = arr[arr >= 20]
print(passed)

[20 30 40]


In [29]:
arr = np.array([10,20,30,40])
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.sum(arr))
print(np.sort(arr))
print(np.argsort(arr))


40
10
25.0
25.0
11.180339887498949
100
[10 20 30 40]
[0 1 2 3]
